Repository Yoast/yoast-test-helper, pull requests merged in 2022-03, with the labels that each got.

#145 Set minimum WP version to 5.8 and tested up to to 5.9
  readme.txt
Labels: changelog: other

#147 Remove the support session feature
  README.md
  readme.txt
  src/plugin.php
  src/support-session.php
Labels: changelog: other

#146 DUPP-284 Introduce button to reset options to defaults
  src/wordpress-plugins/yoast-seo.php
Labels: changelog: other

#148 Fix old version in "wpseo" option after downgrade via Yoast Test Helper
  src/downgrader.php
Labels: changelog: non-user-facing

#149 Fix migration version
  src/downgrader.php
Labels: changelog: non-user-facing

#150 GH Actions: version update for various predefined actions
  .github/workflows/cs.yml
  .github/workflows/deploy.yml
  .github/workflows/lint.yml
  .github/workflows/security.yml
Labels: yoast cs/qa, changelog: non-user-facing
