Repository Yoast/yoast-test-helper, pull requests merged in 2023-11, with the labels that each got.

#205 Set the WordPress tested up to version to 6.4
  readme.txt
Labels: changelog: other

#206 GH Actions: enable linting against PHP 8.3
  .github/workflows/lint.yml
Labels: yoast cs/qa, changelog: other

#208 Composer.json: add link to security policy
  composer.json
Labels: yoast cs/qa

#209 GH Actions: update a few links in inline comments
  .github/workflows/cs.yml
  .github/workflows/deploy.yml
  .github/workflows/lint.yml
Labels: yoast cs/qa

#207 Various small bug fixes
  src/admin-notifications.php
  src/admin-page.php
  src/downgrader.php
  src/feature-toggler.php
  src/plugin-toggler.php
Labels: needs-code-review, yoast cs/qa, changelog: bugfix
