Repository Yoast/yoast-test-helper, pull requests merged in 2023-08, with the labels that each got.

#193 Set the WordPress tested up to version to 6.3
  readme.txt
Labels: changelog: other

#195 Add checkbox to switch to the AI staging api
  src/development-mode.php
Labels: changelog: enhancement

#192 191 test helper php 81 improvements
  .gitignore
  src/domain-dropdown.php
  src/downgrader.php
  src/inline-script.php
  src/plugin-toggler.php
  src/schema.php
  src/xml-sitemaps.php
Labels: changelog: non-user-facing

#196 Set the minimum supported WordPress version to 6.2
  readme.txt
  yoast-test-helper.php
Labels: changelog: other
